### ISSUE TITLE
Error on print statement : Is this library created using Python 3?

### ISSUE THREAD

**Issue by manasgaur** [krzysiekfonal/grammaregex#1]
Traceback (most recent call last):
    from textpipeliner import PipelineEngine, Context
  File "/Library/Python/2.7/site-packages/textpipeliner/__init__.py", line 3, in <module>
    from .pipes import *
  File "/Library/Python/2.7/site-packages/textpipeliner/pipes/__init__.py", line 1, in <module>
    from .pipe import Pipe, \
  File "/Library/Python/2.7/site-packages/textpipeliner/pipes/pipe.py", line 2, in <module>
    from grammaregex import find_tokens, match_tree
  File "/Library/Python/2.7/site-packages/grammaregex/__init__.py", line 1, in <module>
    from .grammaregex import match_tree, find_tokens, print_tree, verify_pattern, PatternSyntaxException
  File "/Library/Python/2.7/site-packages/grammaregex/grammaregex.py", line 70
    print("{", end=" ")

**Comment by patvdleer** [comment]
Pull request #2 should fix this
